import { createProjectPlan } from "./packages/project.core/index.js";

export function createDemoProjectSchedule() {
  return createProjectPlan({
    projectId: "demo-kita-2028",
    projectStart: "2026-06-01",
    tasks: [
      {
        id: "bedarf-klaeren",
        label: "Bedarf und Nutzerprogramm klären",
        owner: "Bauherr",
        phase: "LP1",
        durationDays: 8,
      },
      {
        id: "vorplanung",
        label: "Varianten und Kostenrahmen abstimmen",
        owner: "Architekt",
        phase: "LP2",
        durationDays: 15,
      },
      {
        id: "entwurf",
        label: "Entwurf und Kostenberechnung freigeben",
        owner: "Architekt",
        phase: "LP3",
        durationDays: 20,
      },
      {
        id: "foerdermittel",
        label: "Fördermitteltermin sichern",
        owner: "Projektsteuerer",
        phase: "LP3",
        durationDays: 10,
      },
      {
        id: "genehmigungsmappe",
        label: "Genehmigungsmappe erstellen",
        owner: "Architekt",
        phase: "LP4",
        durationDays: 18,
      },
      {
        id: "behoerdenlauf",
        label: "Behördenlauf und Rückfragen",
        owner: "Behörde",
        phase: "LP4",
        durationDays: 30,
      },
      {
        id: "ausfuehrungsplanung",
        label: "Ausführungsplanung freigeben",
        owner: "Architekt",
        phase: "LP5",
        durationDays: 24,
      },
      {
        id: "rohbau",
        label: "Rohbau beauftragen und starten",
        owner: "Gewerk",
        phase: "LP6-LP8",
        durationDays: 35,
      },
    ],
    dependencies: [
      { from: "bedarf-klaeren", to: "vorplanung", type: "FS", lagDays: 0 },
      { from: "vorplanung", to: "entwurf", type: "FS", lagDays: 0 },
      { from: "entwurf", to: "foerdermittel", type: "SS", lagDays: 5 },
      { from: "entwurf", to: "genehmigungsmappe", type: "FS", lagDays: 2 },
      { from: "foerdermittel", to: "genehmigungsmappe", type: "FF", lagDays: 0 },
      { from: "genehmigungsmappe", to: "behoerdenlauf", type: "FS", lagDays: 0 },
      { from: "behoerdenlauf", to: "ausfuehrungsplanung", type: "FS", lagDays: -5 },
      { from: "ausfuehrungsplanung", to: "rohbau", type: "FS", lagDays: 3 },
    ],
  });
}

export function createDemoProjectRequirements(projectId = "demo-kita-2028") {
  return {
    type: "ProjectRequirementPlan",
    schemaVersion: 1,
    projectId,
    handoverPoints: [
      {
        id: "design-to-permit",
        label: "Entwurf → Genehmigungsplanung",
        phase: "LP3 → LP4",
        targetDate: "2026-08-21",
        benefit: "Bauherr, Planung und Fachplanung bestätigen denselben freigegebenen Ausgangsstand.",
      },
      {
        id: "permit-submission",
        label: "Genehmigungsmappe → Behörde",
        phase: "LP4",
        targetDate: "2026-09-16",
        benefit: "Die Behörde erhält eine klar strukturierte, vollständig zugeordnete Einreichung.",
      },
      {
        id: "execution-release",
        label: "Ausführungsplanung → Vergabe",
        phase: "LP5 → LP6",
        targetDate: "2027-01-18",
        benefit: "Freigegebene Planstände und Leistungsgrundlagen stehen den Vergabepaketen eindeutig zur Verfügung.",
      },
      {
        id: "building-to-operation",
        label: "Bauwerk → Betrieb",
        phase: "LP8 → LP9",
        targetDate: "2028-07-14",
        benefit: "Der Betreiber übernimmt strukturierte Projektdaten zusammen mit den vollständigen Originalquellen.",
      },
    ],
    requirements: [
      {
        id: "approved-design-state",
        title: "Freigegebener Entwurfsstand",
        category: "Planstand",
        accountableRole: "Architekt",
        handoverPointId: "design-to-permit",
        dueDate: "2026-08-14",
        status: "accepted",
        acceptanceCriteria: ["Planstand ist eindeutig versioniert", "Freigabe des Bauherrn ist zugeordnet"],
        sourceRefs: [
          { ref: `/${projectId}/lp3/planstand/v14`, label: "Entwurfsplanung V14", kind: "drawing" },
          { ref: `/${projectId}/journal/freigabe-lp3`, label: "Freigabe LP3", kind: "journal" },
        ],
      },
      {
        id: "cost-calculation-din276",
        title: "Kostenberechnung nach DIN 276",
        category: "Kosten",
        accountableRole: "Projektsteuerer",
        handoverPointId: "design-to-permit",
        dueDate: "2026-08-18",
        status: "ready",
        acceptanceCriteria: ["Kostenstand ist mit dem Entwurfsstand verknüpft", "Kostenfreigabe ist bestätigt"],
        sourceRefs: [{ ref: `/${projectId}/lp3/costs-din276`, label: "Kostenberechnung LP3", kind: "table" }],
      },
      {
        id: "specialist-contributions-lp3",
        title: "Koordinierte Fachplanungsbeiträge",
        category: "Fachplanung",
        accountableRole: "Fachplanung",
        handoverPointId: "design-to-permit",
        dueDate: "2026-08-20",
        status: "inProgress",
        acceptanceCriteria: ["TGA und Brandschutz beziehen sich auf denselben Planstand"],
        sourceRefs: [{ ref: `/${projectId}/lp3/specialist-planning`, label: "Fachplanungsstand LP3", kind: "document-set" }],
      },
      {
        id: "permit-application",
        title: "Bauantrag mit zeichnungsberechtigter Freigabe",
        category: "Genehmigung",
        accountableRole: "Architekt",
        handoverPointId: "permit-submission",
        dueDate: "2026-09-12",
        status: "ready",
        acceptanceCriteria: ["Antragsdaten sind vollständig", "Unterzeichnung ist zugeordnet"],
        sourceRefs: [{ ref: `/${projectId}/lp4/permit-documents/application`, label: "Bauantrag", kind: "form" }],
      },
      {
        id: "fire-safety-evidence",
        title: "Brandschutznachweis",
        category: "Nachweis",
        accountableRole: "Fachplanung",
        handoverPointId: "permit-submission",
        dueDate: "2026-09-14",
        status: "inProgress",
        acceptanceCriteria: ["Nachweis ist dem Genehmigungsstand zugeordnet", "Prüfverantwortung ist benannt"],
        sourceRefs: [{ ref: `/${projectId}/lp4/permit-documents/fire-safety`, label: "Brandschutzkonzept", kind: "evidence" }],
      },
      {
        id: "approved-execution-plans",
        title: "Freigegebene Ausführungspläne",
        category: "Planstand",
        accountableRole: "Architekt",
        handoverPointId: "execution-release",
        dueDate: "2027-01-11",
        status: "planned",
        acceptanceCriteria: ["Jedes Vergabepaket referenziert einen freigegebenen Planstand"],
        sourceRefs: [{ ref: `/${projectId}/lp5/planstand`, label: "Ausführungsplanung", kind: "drawing-set" }],
      },
      {
        id: "tender-scope",
        title: "Abgestimmte Leistungsbeschreibung",
        category: "Vergabe",
        accountableRole: "Architekt",
        handoverPointId: "execution-release",
        dueDate: "2027-01-15",
        status: "planned",
        acceptanceCriteria: ["Leistungsumfang und Planstand sind gegenseitig referenziert"],
        sourceRefs: [{ ref: `/${projectId}/lp6/tender-scope`, label: "Leistungsbeschreibung Rohbau", kind: "document" }],
      },
      {
        id: "as-built-source-set",
        title: "Revisionsunterlagen und Originalquellen",
        category: "Dokumentation",
        accountableRole: "Architekt",
        handoverPointId: "building-to-operation",
        dueDate: "2028-06-28",
        status: "planned",
        acceptanceCriteria: ["Strukturierte Bestandsdaten sind lokal gespeichert", "Gelieferte Originalquellen bleiben vollständig referenziert"],
        sourceRefs: [{ ref: `/${projectId}/lp8/as-built`, label: "Revisionsquellen", kind: "source-set" }],
      },
      {
        id: "operator-acceptance",
        title: "Bestätigte Betreiberübergabe",
        category: "Übergabe",
        accountableRole: "Bauherr",
        handoverPointId: "building-to-operation",
        dueDate: "2028-07-14",
        status: "planned",
        acceptanceCriteria: ["Übernommene Datenbereiche und Quellen sind benannt", "Bestätigung ist im Projektjournal zugeordnet"],
        sourceRefs: [{ ref: `/${projectId}/journal/operator-handover`, label: "Übergabeprotokoll", kind: "journal" }],
      },
    ],
  };
}
